import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { trpc } from "../utils/trpc";

type TechnologyCardProps = {
    name: string;
    description: string;
    documentation: string;
};

interface LinkCardInterface {
    content: string;
    link: string;
}

const linkCardProps: LinkCardInterface[] = [
    { content: "View Computer Sets", link: "/computer_set" },
    { content: "View Computers", link: "/computers" },
    { content: "View Pc Cases", link: "/pc_cases" },
    { content: "View Motherboards", link: "/motherboards" },
    { content: "View CPU", link: "/cpus" },
    { content: "View Coolers", link: "/coolers" },
    { content: "View RAM", link: "/rams" },
    { content: "View GPU", link: "/gpus" },
    { content: "View PSU", link: "/psus" }
];

const LinkCard = (props: LinkCardInterface) => {
    return (
        <div className="flex items-center justify-center">
            <Link
                className="text-lg text-blue-600"
                href={{ pathname: props.link }}
            >
                {props.content}
            </Link>
        </div>
    );
};



const Home: NextPage = () => {
    //   const hello = trpc.useQuery(["example.hello", { text: "Hello" }]);
    //   const squared = trpc.useQuery(["cpu_router.getCpu", { id: 5 }]);

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="container mx-auto py-8">
                <div className="grid grid-cols-3 gap-4">
                    {linkCardProps.map((item, index) => (
                        <div key={index} className="border h-52 flex items-center justify-center text-blue-500 font-semibold hover:bg-orange-200">
                            <LinkCard content={item.content} link={item.link}  />
                        </div>
                    ))}
                </div>
            </main>
        </>
    );
};


export default Home;
